name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allow manuly run
  workflow_dispatch:

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - name: Install packages
        run: npm install
      - name: Build it!
        run: npm run build
